
name: Debug and Investigation

on:
  workflow_dispatch:
    inputs:
      debug_level:
        description: 'Debug Level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - debug
        - verbose
      target_files:
        description: 'Specific files to debug (comma-separated, optional)'
        required: false
        type: string

jobs:
  debug-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Debug build process
      run: |
        echo "🔍 Debugging build with level: ${{ github.event.inputs.debug_level }}"
        
        if [ "${{ github.event.inputs.debug_level }}" = "verbose" ]; then
          DEBUG=* npm run build
        elif [ "${{ github.event.inputs.debug_level }}" = "debug" ]; then
          npm run build -- --verbose
        else
          npm run build
        fi
        
    - name: Debug specific files
      if: github.event.inputs.target_files != ''
      run: |
        IFS=',' read -ra FILES <<< "${{ github.event.inputs.target_files }}"
        for file in "${FILES[@]}"; do
          echo "🔍 Analyzing: $file"
          npx eslint "$file" --format=json || true
          npx prettier --check "$file" || true
          npx tsc --noEmit "$file" || true
        done
        
    - name: Memory and performance analysis
      run: |
        echo "🔍 Performance Analysis"
        
        # Build performance
        time npm run build
        
        # Test performance
        time npm run test || true
        
        # Lint performance
        time npm run lint
        
    - name: Dependency tree analysis
      run: |
        echo "🔍 Dependency Analysis"
        
        # Show dependency tree
        npm ls --depth=2 || true
        
        # Check for security issues
        npm audit --json || true
        
        # Bundle analysis
        npm run bundle:analyze || true
        
    - name: Generate debug report
      run: |
        echo "## 🐛 Debug Report" > debug-report.md
        echo "**Timestamp:** $(date)" >> debug-report.md
        echo "**Debug Level:** ${{ github.event.inputs.debug_level }}" >> debug-report.md
        echo "**Target Files:** ${{ github.event.inputs.target_files }}" >> debug-report.md
        echo "" >> debug-report.md
        echo "### Build Output" >> debug-report.md
        echo "\`\`\`" >> debug-report.md
        ls -la dist/ >> debug-report.md || echo "No dist directory found" >> debug-report.md
        echo "\`\`\`" >> debug-report.md
        
    - name: Upload debug artifacts
      uses: actions/upload-artifact@v4
      with:
        name: debug-analysis-${{ github.run_number }}
        path: |
          debug-report.md
          *.json
          *.log
          dist/
        retention-days: 7
